export default [
    {Code: 'AD',	Name: 'Andorra'},
    {Code: 'AE',	Name: 'Emiratos Árabes Unidos'},
    {Code: 'AF',	Name: 'Afganistán'},
    {Code: 'AG',	Name: 'Antigua y Barbuda'},
    {Code: 'AI',	Name: 'Anguila'},
    {Code: 'AL',	Name: 'Albania'},
    {Code: 'AM',	Name: 'Armenia'},
    {Code: 'AN',	Name: 'Antillas Neerlandesas'},
    {Code: 'AO',	Name: 'Angola'},
    {Code: 'AQ',	Name: 'Antártida'},
    {Code: 'AR',	Name: 'Argentina'},
    {Code: 'AS',	Name: 'Samoa Americana'},
    {Code: 'AT',	Name: 'Austria'},
    {Code: 'AU',	Name: 'Australia'},
    {Code: 'AW',	Name: 'Aruba'},
    {Code: 'AX',	Name: 'Islas Áland'},
    {Code: 'AZ',	Name: 'Azerbaiyán'},
    {Code: 'BA',	Name: 'Bosnia y Herzegovina'},
    {Code: 'BB',	Name: 'Barbados'},
    {Code: 'BD',	Name: 'Bangladesh'},
    {Code: 'BE',	Name: 'Bélgica'},
    {Code: 'BF',	Name: 'Burkina Faso'},
    {Code: 'BG',	Name: 'Bulgaria'},
    {Code: 'BH',	Name: 'Bahréin'},
    {Code: 'BI',	Name: 'Burundi'},
    {Code: 'BJ',	Name: 'Benin'},
    {Code: 'BL',	Name: 'San Bartolomé'},
    {Code: 'BM',	Name: 'Bermudas'},
    {Code: 'BN',	Name: 'Brunéi'},
    {Code: 'BO',	Name: 'Bolivia'},
    {Code: 'BR',	Name: 'Brasil'},
    {Code: 'BS',	Name: 'Bahamas'},
    {Code: 'BT',	Name: 'Bhután'},
    {Code: 'BV',	Name: 'Isla Bouvet'},
    {Code: 'BW',	Name: 'Botsuana'},
    {Code: 'BY',	Name: 'Belarús'},
    {Code: 'BZ',	Name: 'Belice'},
    {Code: 'CA',	Name: 'Canadá'},
    {Code: 'CC',	Name: 'Islas Cocos'},
    {Code: 'CF',	Name: 'República Centro-Africana'},
    {Code: 'CG',	Name: 'Congo'},
    {Code: 'CH',	Name: 'Suiza'},
    {Code: 'CI',	Name: 'Costa de Marfil'},
    {Code: 'CK',	Name: 'Islas Cook'},
    {Code: 'CL',	Name: 'Chile'},
    {Code: 'CM',	Name: 'Camerún'},
    {Code: 'CN',	Name: 'China'},
    {Code: 'CO',	Name: 'Colombia'},
    {Code: 'CR',	Name: 'Costa Rica'},
    {Code: 'CU',	Name: 'Cuba'},
    {Code: 'CV',	Name: 'Cabo Verde'},
    {Code: 'CX',	Name: 'Islas Christmas'},
    {Code: 'CY',	Name: 'Chipre'},
    {Code: 'CZ',	Name: 'República Checa'},
    {Code: 'DE',	Name: 'Alemania'},
    {Code: 'DJ',	Name: 'Yibuti'},
    {Code: 'DK',	Name: 'Dinamarca'},
    {Code: 'DM',	Name: 'Domínica'},
    {Code: 'DO',	Name: 'República Dominicana'},
    {Code: 'DZ',	Name: 'Argel'},
    {Code: 'EC',	Name: 'Ecuador'},
    {Code: 'EE',	Name: 'Estonia'},
    {Code: 'EG',	Name: 'Egipto'},
    {Code: 'EH',	Name: 'Sahara Occidental'},
    {Code: 'ER',	Name: 'Eritrea'},
    {Code: 'ES',	Name: 'España'},
    {Code: 'ET',	Name: 'Etiopía'},
    {Code: 'FI',	Name: 'Finlandia'},
    {Code: 'FJ',	Name: 'Fiji'},
    {Code: 'FK',	Name: 'Islas Malvinas'},
    {Code: 'FM',	Name: 'Micronesia'},
    {Code: 'FO',	Name: 'Islas Faroe'},
    {Code: 'FR',	Name: 'Francia'},
    {Code: 'GA',	Name: 'Gabón'},
    {Code: 'GB',	Name: 'Reino Unido'},
    {Code: 'GD',	Name: 'Granada'},
    {Code: 'GE',	Name: 'Georgia'},
    {Code: 'GF',	Name: 'Guayana Francesa'},
    {Code: 'GG',	Name: 'Guernsey'},
    {Code: 'GH',	Name: 'Ghana'},
    {Code: 'GI',	Name: 'Gibraltar'},
    {Code: 'GL',	Name: 'Groenlandia'},
    {Code: 'GM',	Name: 'Gambia'},
    {Code: 'GN',	Name: 'Guinea'},
    {Code: 'GP',	Name: 'Guadalupe'},
    {Code: 'GQ',	Name: 'Guinea Ecuatorial'},
    {Code: 'GR',	Name: 'Grecia'},
    {Code: 'GS',	Name: 'Georgia del Sur e Islas Sandwich del Sur'},
    {Code: 'GT',	Name: 'Guatemala'},
    {Code: 'GU',	Name: 'Guam'},
    {Code: 'GW',	Name: 'Guinea-Bissau'},
    {Code: 'GY',	Name: 'Guayana'},
    {Code: 'HK',	Name: 'Hong Kong'},
    {Code: 'HM',	Name: 'Islas Heard y McDonald'},
    {Code: 'HN',	Name: 'Honduras'},
    {Code: 'HR',	Name: 'Croacia'},
    {Code: 'HT',	Name: 'Haití'},
    {Code: 'HU',	Name: 'Hungría'},
    {Code: 'ID',	Name: 'Indonesia'},
    {Code: 'IE',	Name: 'Irlanda'},
    {Code: 'IL',	Name: 'Israel'},
    {Code: 'IM',	Name: 'Isla de Man'},
    {Code: 'IN',	Name: 'India'},
    {Code: 'IO',	Name: 'Territorio Británico del Océano Índico'},
    {Code: 'IQ',	Name: 'Irak'},
    {Code: 'IR',	Name: 'Irán'},
    {Code: 'IS',	Name: 'Islandia'},
    {Code: 'IT',	Name: 'Italia'},
    {Code: 'JE',	Name: 'Jersey'},
    {Code: 'JM',	Name: 'Jamaica'},
    {Code: 'JO',	Name: 'Jordania'},
    {Code: 'JP',	Name: 'Japón'},
    {Code: 'KE',	Name: 'Kenia'},
    {Code: 'KG',	Name: 'Kirguistán'},
    {Code: 'KH',	Name: 'Camboya'},
    {Code: 'KI',	Name: 'Kiribati'},
    {Code: 'KM',	Name: 'Comoros'},
    {Code: 'KN',	Name: 'San Cristóbal y Nieves'},
    {Code: 'KP',	Name: 'Corea del Norte'},
    {Code: 'KR',	Name: 'Corea del Sur'},
    {Code: 'KW',	Name: 'Kuwait'},
    {Code: 'KY',	Name: 'Islas Caimán'},
    {Code: 'KZ',	Name: 'Kazajstán'},
    {Code: 'LA',	Name: 'Laos'},
    {Code: 'LB',	Name: 'Líbano'},
    {Code: 'LC',	Name: 'Santa Lucía'},
    {Code: 'LI',	Name: 'Liechtenstein'},
    {Code: 'LK',	Name: 'Sri Lanka'},
    {Code: 'LR',	Name: 'Liberia'},
    {Code: 'LS',	Name: 'Lesotho'},
    {Code: 'LT',	Name: 'Lituania'},
    {Code: 'LU',	Name: 'Luxemburgo'},
    {Code: 'LV',	Name: 'Letonia'},
    {Code: 'LY',	Name: 'Libia'},
    {Code: 'MA',	Name: 'Marruecos'},
    {Code: 'MC',	Name: 'Mónaco'},
    {Code: 'MD',	Name: 'Moldova'},
    {Code: 'ME',	Name: 'Montenegro'},
    {Code: 'MG',	Name: 'Madagascar'},
    {Code: 'MH',	Name: 'Islas Marshall'},
    {Code: 'MK',	Name: 'Macedonia'},
    {Code: 'ML',	Name: 'Mali'},
    {Code: 'MM',	Name: 'Myanmar'},
    {Code: 'MN',	Name: 'Mongolia'},
    {Code: 'MO',	Name: 'Macao'},
    {Code: 'MQ',	Name: 'Martinica'},
    {Code: 'MR',	Name: 'Mauritania'},
    {Code: 'MS',	Name: 'Montserrat'},
    {Code: 'MT',	Name: 'Malta'},
    {Code: 'MU',	Name: 'Mauricio'},
    {Code: 'MV',	Name: 'Maldivas'},
    {Code: 'MW',	Name: 'Malawi'},
    {Code: 'MX',	Name: 'México'},
    {Code: 'MY',	Name: 'Malasia'},
    {Code: 'MZ',	Name: 'Mozambique'},
    {Code: 'NA',	Name: 'Namibia'},
    {Code: 'NC',	Name: 'Nueva Caledonia'},
    {Code: 'NE',	Name: 'Níger'},
    {Code: 'NF',	Name: 'Islas Norkfolk'},
    {Code: 'NG',	Name: 'Nigeria'},
    {Code: 'NI',	Name: 'Nicaragua'},
    {Code: 'NL',	Name: 'Países Bajos'},
    {Code: 'NO',	Name: 'Noruega'},
    {Code: 'NP',	Name: 'Nepal'},
    {Code: 'NR',	Name: 'Nauru'},
    {Code: 'NU',	Name: 'Niue'},
    {Code: 'NZ',	Name: 'Nueva Zelanda'},
    {Code: 'OM',	Name: 'Omán'},
    {Code: 'PA',	Name: 'Panamá'},
    {Code: 'PE',	Name: 'Perú'},
    {Code: 'PF',	Name: 'Polinesia Francesa'},
    {Code: 'PG',	Name: 'Papúa Nueva Guinea'},
    {Code: 'PH',	Name: 'Filipinas'},
    {Code: 'PK',	Name: 'Pakistán'},
    {Code: 'PL',	Name: 'Polonia'},
    {Code: 'PM',	Name: 'San Pedro y Miquelón'},
    {Code: 'PN',	Name: 'Islas Pitcairn'},
    {Code: 'PR',	Name: 'Puerto Rico'},
    {Code: 'PS',	Name: 'Palestina'},
    {Code: 'PT',	Name: 'Portugal'},
    {Code: 'PW',	Name: 'Islas Palaos'},
    {Code: 'PY',	Name: 'Paraguay'},
    {Code: 'QA',	Name: 'Qatar'},
    {Code: 'RE',	Name: 'Reunión'},
    {Code: 'RO',	Name: 'Rumanía'},
    {Code: 'RS',	Name: 'Serbia y Montenegro'},
    {Code: 'RU',	Name: 'Rusia'},
    {Code: 'RW',	Name: 'Ruanda'},
    {Code: 'SA',	Name: 'Arabia Saudita'},
    {Code: 'SB',	Name: 'Islas Solomón'},
    {Code: 'SC',	Name: 'Seychelles'},
    {Code: 'SD',	Name: 'Sudán'},
    {Code: 'SE',	Name: 'Suecia'},
    {Code: 'SG',	Name: 'Singapur'},
    {Code: 'SH',	Name: 'Santa Elena'},
    {Code: 'SI',	Name: 'Eslovenia'},
    {Code: 'SJ',	Name: 'Islas Svalbard y Jan Mayen'},
    {Code: 'SK',	Name: 'Eslovaquia'},
    {Code: 'SL',	Name: 'Sierra Leona'},
    {Code: 'SM',	Name: 'San Marino'},
    {Code: 'SN',	Name: 'Senegal'},
    {Code: 'SO',	Name: 'Somalia'},
    {Code: 'SR',	Name: 'Surinam'},
    {Code: 'ST',	Name: 'Santo Tomé y Príncipe'},
    {Code: 'SV',	Name: 'El Salvador'},
    {Code: 'SY',	Name: 'Siria'},
    {Code: 'SZ',	Name: 'Suazilandia'},
    {Code: 'TC',	Name: 'Islas Turcas y Caicos'},
    {Code: 'TD',	Name: 'Chad'},
    {Code: 'TF',	Name: 'Territorios Australes Franceses'},
    {Code: 'TG',	Name: 'Togo'},
    {Code: 'TH',	Name: 'Tailandia'},
    {Code: 'TH',	Name: 'Tanzania'},
    {Code: 'TJ',	Name: 'Tayikistán'},
    {Code: 'TK',	Name: 'Tokelau'},
    {Code: 'TL',	Name: 'Timor-Leste'},
    {Code: 'TM',	Name: 'Turkmenistán'},
    {Code: 'TN',	Name: 'Túnez'},
    {Code: 'TO',	Name: 'Tonga'},
    {Code: 'TR',	Name: 'Turquía'},
    {Code: 'TT',	Name: 'Trinidad y Tobago'},
    {Code: 'TV',	Name: 'Tuvalu'},
    {Code: 'TW',	Name: 'Taiwán'},
    {Code: 'UA',	Name: 'Ucrania'},
    {Code: 'UG',	Name: 'Uganda'},
    {Code: 'US',	Name: 'Estados Unidos de América'},
    {Code: 'UY',	Name: 'Uruguay'},
    {Code: 'UZ',	Name: 'Uzbekistán'},
    {Code: 'VA',	Name: 'Ciudad del Vaticano'},
    {Code: 'VC',	Name: 'San Vicente y las Granadinas'},
    {Code: 'VE',	Name: 'Venezuela'},
    {Code: 'VG',	Name: 'Islas Vírgenes Británicas'},
    {Code: 'VI',	Name: 'Islas Vírgenes de los Estados Unidos de América'},
    {Code: 'VN',	Name: 'Vietnam'},
    {Code: 'VU',	Name: 'Vanuatu'},
    {Code: 'WF',	Name: 'Wallis y Futuna'},
    {Code: 'WS',	Name: 'Samoa'},
    {Code: 'YE',	Name: 'Yemen'},
    {Code: 'YT',	Name: 'Mayotte'},
    {Code: 'ZA',	Name: 'Sudáfrica'},
];