export default [
    {Code: 'AR-A',	Name: 'Salta'},
    {Code: 'AR-B',	Name: 'Provincia de Buenos Aires'},
    {Code: 'AR-C',	Name: 'Ciudad Autónoma de Buenos Aires'},
    {Code: 'AR-D',	Name: 'San Luis'},
    {Code: 'AR-E',	Name: 'Entre Ríos'},
    {Code: 'AR-F',	Name: 'La Rioja'},
    {Code: 'AR-G',	Name: 'Santiago del Estero'},
    {Code: 'AR-H',	Name: 'Chaco'},
    {Code: 'AR-J',	Name: 'San Juan'},
    {Code: 'AR-K',	Name: 'Catamarca'},
    {Code: 'AR-L',	Name: 'La Pampa'},
    {Code: 'AR-M',	Name: 'Mendoza'},
    {Code: 'AR-N',	Name: 'Misiones'},
    {Code: 'AR-P',	Name: 'Formosa'},
    {Code: 'AR-Q',	Name: 'Neuquén'},
    {Code: 'AR-R',	Name: 'Río Negro'},
    {Code: 'AR-S',	Name: 'Santa Fe'},
    {Code: 'AR-T',	Name: 'Tucumán'},
    {Code: 'AR-U',	Name: 'Chubut'},
    {Code: 'AR-V',	Name: 'Tierra del Fuego'},
    {Code: 'AR-W',	Name: 'Corrientes'},
    {Code: 'AR-X',	Name: 'Córdoba'},
    {Code: 'AR-Y',	Name: 'Jujuy'},
    {Code: 'AR-Z',	Name: 'Santa Cruz'},
];